// <auto-generated />
using Data.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220128092040_PortfolioDb")]
    partial class PortfolioDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "1.jpg",
                            IsDeleted = false,
                            Title = "test title"
                        },
                        new
                        {
                            Id = 2,
                            Image = "1.jpg",
                            IsDeleted = false,
                            Title = "test title"
                        },
                        new
                        {
                            Id = 3,
                            Image = "1.jpg",
                            IsDeleted = false,
                            Title = "test title"
                        },
                        new
                        {
                            Id = 4,
                            Image = "1.jpg",
                            IsDeleted = false,
                            Title = "test title"
                        },
                        new
                        {
                            Id = 5,
                            Image = "1.jpg",
                            IsDeleted = false,
                            Title = "test title"
                        },
                        new
                        {
                            Id = 6,
                            Image = "1.jpg",
                            IsDeleted = false,
                            Title = "test title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
